issues.txt
sunlight.net https://github.com/AdguardTeam/AdguardFilters/issues/12461
=> sunlight.net - fixing auth

sensitive.txt
https://github.com/AdguardTeam/AdguardForMac/issues/286
=> remove lazerpenguin.com

banks.txt
americanexpress.com https://github.com/AdguardTeam/AdguardFilters/issues/13630
=> fix #13630

banks.txt
https://github.com/AdguardTeam/AdguardFilters/issues/15116
=> Fix AdguardFilters#15116

banks.txt
For internet banking and mobile app they use `george.slsp.sk`, and may be some other domains.
=> ib.slsp.sk -> slsp.sk

issues.txt
New HTTPS exclusion has been added.
// https://github.com/AdguardTeam/AdguardForWindows/issues/2294
=> HTTPS Exclusions update.txt

banks.txt
https://github.com/AdguardTeam/AdguardFilters/issues/20548
=> ambank.amonline.com.my

issues.txt
https://github.com/AdguardTeam/AdguardFilters/issues/24131
=> charts.profinance.ru - fixing graph

exclusions/issues.txt
https://github.com/AdguardTeam/AdguardFilters/issues/35553
=> Fix control.phone.com 

exclusions/mac.txt
https://github.com/AdguardTeam/CoreLibs/issues/1084
=> temporary fix re-store.ru

exclusions/mac.txt
https://github.com/AdguardTeam/CoreLibs/issues/1097
=> temporary fix antonioli.eu

exclusions/banks.txt
https://forum.adguard.com/index.php?threads/hsbc-blank-page.35032/
=> Update banks.txt US.hsbc.com

exclusions/mac.txt
https://github.com/AdguardTeam/CoreLibs/issues/1094#issuecomment-533073030
=> Fix #197 emploiquebec.gouv.qc.ca

exclusions/issues.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/203
=> Fix #203 console.cloud.google.com

exclusions/banks.txt
=> Added new bank site 🚀

exclusions/android.txt
This is the solution for the Android task: https://github.com/AdguardTeam/AdguardForAndroid/issues/3052
=> Added new application exclusions

exclusions/banks.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/222
=> fix #222 - anz.com bank

exclusions/firefox.txt
https://github.com/AdguardTeam/AdguardForWindows/issues/2981
=> issue #win2981, basic resolve

exclusions/sensitive.txt
Add static.adguard.com to HTTPS exclusions
=> issue #AG-50, basic resolve

exclusions/android.txt
https://github.com/AdguardTeam/AdguardForAndroid/issues/3324
=> Add HTTPS exclusions for com.plexapp.android hosts

exclusions/issues.txt
https://github.com/AdguardTeam/CoreLibs/issues/1280
=> Fix LINE extension

exclusions/android.txt
https://github.com/AdguardTeam/AdguardForAndroid/issues/3255
=> Add new HTTPS exclusions for Railcard app

exclusions/android.txt
https://github.com/AdguardTeam/AdguardForAndroid/issues/3328
=> Add new HTTPS exclusions for Android apps

exclusions/banks.txt
=> banks_update

exclusions/issues.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/289
=> Fix #289 e-tjanster.1177.se

exclusions/issues.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/300
=> Fix #300 icloud.com

exclusions/banks.txt
This PR adds chilean banks (and some important chilean financial institutions) to banks.txt
=> Add chilean banks to exclusions

exclusions/banks.txt
French language version of the bpostbank.be website.
Go to https://www.bpostbank.be/bpb/bdigital/francais ...
... and you will be redirected soon after to the bpostbanque.be domain name. :heavy_check_mark:
=> Add bpostbanque.be to banks.txt

exclusions/sensitive.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/311
=> Fix #311 intelink.gov

exclusions/banks.txt, exclusions/issues.txt, exclusions/sensitive.txt
#331 #324 #323 #321 #322 #330 #325
=> Exclusions update

exclusions/banks.txt
Add some indonesia Bank
BTPN
Jenius
Bank DKI
Bank Bukopin
=> Add some Indonesia Bank

exclusions/sensitive.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/348
=> Fix #348 tikker.emta.ee

exclusions/android.txt, exclusions/banks.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/356
https://github.com/AdguardTeam/HttpsExclusions/issues/357
=> Exclusionsupd

exclusions/banks.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/375
https://github.com/AdguardTeam/HttpsExclusions/issues/374
https://github.com/AdguardTeam/HttpsExclusions/issues/376
=> Exclusions777

exclusions/android.txt
Reverts AdguardTeam/HttpsExclusions#384
=> Revert "Exclusions777"

exclusions/issues.txt
https://github.com/AdguardTeam/AdguardFilters/issues/77058
=> fix #77058 shazam.com

exclusions/sensitive.txt
A site with medical information about a person for residents of St. Petersburg.
=> Add gorzdrav.spb.ru

exclusions/banks.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/363
HTTPS exclusions for banking apps(same domains used by web versions)
https://play.google.com/store/apps/details?id=com.bsm.activity2
https://play.google.com/store/apps/details?id=id.dana
https://play.google.com/store/apps/details?id=id.flip
https://play.google.com/store/apps/details?id=src.com.bni
=> Fix #363 Indonesian wallets #363

exclusions/sensitive.txt
https://proton.me/blog/protonme-domain
=> Add new ProtonMail domain

exclusions/banks.txt
It looks like this list missed a few banks and other financial services, so I'm adding them directly via this PR. The first commit is a list I put together, the rest are from the issues linked to this PR.
Allow edit to maintainer option is turned on, so people with merge access should feel free to modify the PR if that's needed before merge.
Issue links:
* resolves #491
* resolves #483
* resolves #492
=> Add various banks to exclusion list

exclusions/banks.txt
=> Add bitso.com to banks.txt

exclusions/banks.txt
Please accept the PR. @ameshkov
=> online.peple.com.tr (Digital Bank Website)

exclusions/mac.txt
https://github.com/AdguardTeam/HttpsExclusions/issues/520
=> Fix #520 icloud.com.cn

exclusions/banks.txt
https://github.com/AdguardTeam/AdguardFilters/issues/145220
=> Fix secure.royalbank.com 

exclusions/banks.txt
Payment service of wayforpay.com
=> Added secure.wayforpay.com

exclusions/sensitive.txt
https://github.com/AdguardTeam/AdguardFilters/issues/160593
=> Fix bitwarden.eu

exclusions/banks.txt
Questrade is a financial service where you can buy stocks and etfs. They also now sell mortgages (I think)
https://www.questrade.com/home
the rest were taken from the top 10 biggest credit unions in Canada list
=> Add more financial service exclusions

exclusions/banks.txt
Exclusions for yandex financial services
=> Exclusions for yandex payments

exclusions/banks.txt
https://www.accessoires-informatiques.com/Index/secure
=> wlp-acs.com - 3d secure domain

exclusions/banks.txt, exclusions/sensitive.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/576
=> Add vostok.bank, pki-auth.monobank.com.ua and app.deel.com

exclusions/android.txt
=> added opera wallpaper api

exclusions/android.txt
Added new lines from updated ag-android exlusions file
=> update android current entries

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/583
=> Add Veridian & Transamerica

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/587
Fix https://github.com/AdguardTeam/AdguardFilters/issues/178796
=> Add Banco Nacional de Costa Rica

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/589
=> Add HNB, Sampath Bank, and Commercial Bank of Ceylon Online Bankin

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/592
=> Add Travis Credit Union

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/598
=> Fix tbank.ru

exclusions/banks.txt
https://en.wikipedia.org/wiki/Hana_Bank
=> Add hanabank.com

exclusions/banks.txt
=> add quirion.de and quirinprivatbank.de

exclusions/banks.txt
=> add hsbc.lk

exclusions/sensitive.txt
=> Add synology DDNS

exclusions/banks.txt
https://play.google.com/store/apps/details?id=viva.republica.toss
=> Add toss bank

exclusions/issues.txt
resolves https://github.com/AdguardTeam/AdguardForWindows/issues/5268
=> Added copilot.microsoft.com to HTTPS exclusions

exclusions/issues.txt
Reverts AdguardTeam/HttpsExclusions#612
=> Revert "Added copilot.microsoft.com to HTTPS exclusions"

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/614
=> Add Australian St George bank

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/610
=> add hellobank.fr

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/617
=> add traderepublic.com

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/616
=> add bolero.be

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/618
=> add xtb.com

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/620
=> Fix personalbanking.bankofireland.com

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/619
=> Fix personas.bancobcr.com

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/620
=> fix fintro.be

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/633
=> add some bank domains

exclusions/banks.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/636
=> Fix takasbank.com.tr

exclusions/banks.txt
Fix https://github.com/AdguardTeam/AdguardFilters/issues/201072
=> Fix payment-gateway.tosspayments.com

exclusions/banks.txt
There is also a fix for other issues:
https://github.com/AdguardTeam/HttpsExclusions/issues/650
https://github.com/AdguardTeam/HttpsExclusions/issues/649
https://github.com/AdguardTeam/HttpsExclusions/issues/648
https://github.com/AdguardTeam/HttpsExclusions/issues/647
https://github.com/AdguardTeam/HttpsExclusions/issues/646
=> Fix #651 Additional credit unions

exclusions/issues.txt
=> Fix #656 gw.buaa.edu.cn

exclusions/android.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/654
=> Fix AdguardTeam/HttpsExclusions#654 dropbox.com

exclusions/sensitive.txt
Fix https://github.com/AdguardTeam/HttpsExclusions/issues/574
=> blog.lastpass.com

exclusions/sensitive.txt
=> Fix #667 Spanish Government websites

exclusions/banks.txt
https://en.wikipedia.org/wiki/KakaoPay
https://developers.kakaopay.com/docs/getting-started/basic/developers-intro
=> Add some Kakao Pay domains

exclusions/banks.txt
A Card service of https://en.wikipedia.org/wiki/Hana_Bank
=> Add hanacard.co.kr

exclusions/sensitive.txt
https://en.wikipedia.org/wiki/I-PIN
To test it, please try to sign up PlayStation Network as a person living in South Korea.
=> Add NICE iPiN service

exclusions/issues.txt
Fix AdguardTeam/AdguardFilters#211633
=> Fix Equicord
